### ISSUE TITLE
restore from EBS snapshot (or other backup)

### ISSUE THREAD

**Issue by flippyhead** [ThoughtWorksStudios/elasticsearch-opsworks#1]
I'm hoping to migrate to this setup from an existing one. I've got my current ES data mounted on EBS volumes (on a two instance cluster) and I'm trying to understand how to migrate the data using your setup. Do you have any suggestions? I'm a bit new to cloud formation and opsworks (but not chef) and it's not obvious to me how I'd go about creating my EBS volumes from a snap shot or otherwise importing (perhaps via S3) my ES data.

Re-indexing isn't an option as ES is my primary datastore. 

Thanks again for building all this!

**Comment by wpc** [comment]
Hi, flippyhead:
If your data is not large, try https://github.com/taskrabbit/elasticsearch-dump, otherwise
- Setup a 1 instance cluster (INSTANCE_COUNT=1)
- SSH into the instance
- Download your elasticsearch data (maybe from S3), and unpack.
- Stop elasticsearch service
- Replace /mnt/elasticsearch-data with your data
- Start elasticsearch service
- Bump up INSTANCE_COUNT to the cluster size you prefer and redeploy.
- Monitoring to see data get balanced through the cluster

Given all we did before is reindexing in this situation, I can not guarantee the way I described works. But seems straightforward and worth trying.
